2025-03-24 23:59:54,576 - ImageProcessor - INFO - 程序启动
2025-03-24 23:59:54,577 - ImageProcessor - INFO - 操作系统: win32
2025-03-24 23:59:54,577 - ImageProcessor - INFO - Python版本: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
2025-03-25 00:00:02,914 - ImageProcessor - INFO - 收到拖拽数据: [PySide6.QtCore.QUrl('file:///C:/Users/Yt/Desktop/img/????????/?????_20250323211417.jpg')]
2025-03-25 00:00:02,915 - ImageProcessor - DEBUG - 正在解析拖拽数据: [PySide6.QtCore.QUrl('file:///C:/Users/Yt/Desktop/img/????????/?????_20250323211417.jpg')]
2025-03-25 00:00:02,916 - ImageProcessor - DEBUG - 添加有效路径: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211417.jpg
2025-03-25 00:00:02,916 - ImageProcessor - INFO - 最终解析结果: ['C:\\Users\\Yt\\Desktop\\img\\新建文件夹\\微信图片_20250323211417.jpg']
2025-03-25 00:00:02,918 - ImageProcessor - INFO - 解析后的文件列表: ['C:\\Users\\Yt\\Desktop\\img\\新建文件夹\\微信图片_20250323211417.jpg']
2025-03-25 00:00:02,918 - ImageProcessor - DEBUG - 处理文件: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211417.jpg
2025-03-25 00:00:02,919 - ImageProcessor - DEBUG - 有效图片文件: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211417.jpg
2025-03-25 00:00:02,919 - ImageProcessor - INFO - 添加了 1 个文件，有效添加 1 个（去重后）
2025-03-25 00:00:02,956 - ImageProcessor - DEBUG - 成功预览图片
2025-03-25 00:00:06,080 - ImageProcessor - INFO - 收到拖拽数据: [PySide6.QtCore.QUrl('file:///C:/Users/Yt/Desktop/img/????????/?????_20250323211349.jpg'), PySide6.QtCore.QUrl('file:///C:/Users/Yt/Desktop/img/????????/?????_20250323211400.jpg'), PySide6.QtCore.QUrl('file:///C:/Users/Yt/Desktop/img/????????/?????_20250323211417.jpg')]
2025-03-25 00:00:06,080 - ImageProcessor - DEBUG - 正在解析拖拽数据: [PySide6.QtCore.QUrl('file:///C:/Users/Yt/Desktop/img/????????/?????_20250323211349.jpg'), PySide6.QtCore.QUrl('file:///C:/Users/Yt/Desktop/img/????????/?????_20250323211400.jpg'), PySide6.QtCore.QUrl('file:///C:/Users/Yt/Desktop/img/????????/?????_20250323211417.jpg')]
2025-03-25 00:00:06,081 - ImageProcessor - DEBUG - 添加有效路径: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211349.jpg
2025-03-25 00:00:06,081 - ImageProcessor - DEBUG - 添加有效路径: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211400.jpg
2025-03-25 00:00:06,081 - ImageProcessor - DEBUG - 添加有效路径: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211417.jpg
2025-03-25 00:00:06,081 - ImageProcessor - INFO - 最终解析结果: ['C:\\Users\\Yt\\Desktop\\img\\新建文件夹\\微信图片_20250323211349.jpg', 'C:\\Users\\Yt\\Desktop\\img\\新建文件夹\\微信图片_20250323211400.jpg', 'C:\\Users\\Yt\\Desktop\\img\\新建文件夹\\微信图片_20250323211417.jpg']
2025-03-25 00:00:06,081 - ImageProcessor - INFO - 解析后的文件列表: ['C:\\Users\\Yt\\Desktop\\img\\新建文件夹\\微信图片_20250323211349.jpg', 'C:\\Users\\Yt\\Desktop\\img\\新建文件夹\\微信图片_20250323211400.jpg', 'C:\\Users\\Yt\\Desktop\\img\\新建文件夹\\微信图片_20250323211417.jpg']
2025-03-25 00:00:06,081 - ImageProcessor - DEBUG - 处理文件: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211349.jpg
2025-03-25 00:00:06,082 - ImageProcessor - DEBUG - 有效图片文件: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211349.jpg
2025-03-25 00:00:06,082 - ImageProcessor - DEBUG - 处理文件: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211400.jpg
2025-03-25 00:00:06,082 - ImageProcessor - DEBUG - 有效图片文件: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211400.jpg
2025-03-25 00:00:06,082 - ImageProcessor - DEBUG - 处理文件: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211417.jpg
2025-03-25 00:00:06,082 - ImageProcessor - DEBUG - 有效图片文件: C:\Users\Yt\Desktop\img\新建文件夹\微信图片_20250323211417.jpg
2025-03-25 00:00:06,082 - ImageProcessor - INFO - 添加了 3 个文件，有效添加 2 个（去重后）
2025-03-25 00:00:06,109 - ImageProcessor - DEBUG - 成功预览图片
2025-03-25 00:00:08,128 - ImageProcessor - INFO - 初始化OCR引擎，使用语言: ['ch_sim', 'en']
2025-03-25 00:00:08,129 - ImageProcessor - INFO - NVIDIA GPU加速状态: 不可用
2025-03-25 00:00:45,846 - ImageProcessor.ProcessThread - ERROR - 处理图片 微信图片_20250323211349.jpg 时出错: No module named 'sklearn'
Traceback (most recent call last):
  File "C:\GitHub\ORC\main.py", line 233, in process_single_image
    confidence = self.calculate_confidence_score(results, angle)
  File "C:\GitHub\ORC\main.py", line 408, in calculate_confidence_score
    columns = detect_columns(centers[:, 0])
  File "C:\GitHub\ORC\main.py", line 401, in detect_columns
    from sklearn.cluster import DBSCAN
ModuleNotFoundError: No module named 'sklearn'
2025-03-25 00:00:46,113 - ImageProcessor.ProcessThread - ERROR - 处理图片 微信图片_20250323211400.jpg 时出错: No module named 'sklearn'
Traceback (most recent call last):
  File "C:\GitHub\ORC\main.py", line 233, in process_single_image
    confidence = self.calculate_confidence_score(results, angle)
  File "C:\GitHub\ORC\main.py", line 408, in calculate_confidence_score
    columns = detect_columns(centers[:, 0])
  File "C:\GitHub\ORC\main.py", line 401, in detect_columns
    from sklearn.cluster import DBSCAN
ModuleNotFoundError: No module named 'sklearn'
2025-03-25 00:00:46,358 - ImageProcessor.ProcessThread - ERROR - 处理图片 微信图片_20250323211417.jpg 时出错: No module named 'sklearn'
Traceback (most recent call last):
  File "C:\GitHub\ORC\main.py", line 233, in process_single_image
    confidence = self.calculate_confidence_score(results, angle)
  File "C:\GitHub\ORC\main.py", line 408, in calculate_confidence_score
    columns = detect_columns(centers[:, 0])
  File "C:\GitHub\ORC\main.py", line 401, in detect_columns
    from sklearn.cluster import DBSCAN
ModuleNotFoundError: No module named 'sklearn'
